language: csharp
solution: Cielo.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
install:
  - sudo apt-get install nunit-console
  - nuget restore Cielo.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild Cielo.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Cielo.Tests/bin/Debug/Cielo.Tests.dll