language: csharp
solution: Cielo.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
install:
  - sudo apt-get install nunit-console
  - nuget restore Cielo.sln
script:
  - xbuild ./Cielo.sln
  - nunit-console ./Cielo.Tests/bin/Debug/Cielo.Tests.dll